name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file Awx-automation/Awx-automation/pom.xml

    - name: Unit Test
      run: mvn -B test --file Awx-automation/Awx-automation/pom.xml


    - name: Build docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Awx-automation/Awx-automation/Dockerfile 
        push: false
        tags: ${{ secrets.DOCKER_LOGIN }}/awx-automation:latest 

    - name: Login to Docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: push to docker hub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Awx-automation/Awx-automation/Dockerfile  
        push: true
        tags: ${{ secrets.DOCKER_LOGIN }}/awx-automation:latest