name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: List files after checkout # Keep this for verification
      run: ls -lR

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      working-directory: Awx-automation/Awx-automation # Verify this path is EXACTLY correct
      run: mvn -B package

    # --- Check this step carefully ---
    - name: Update dependency graph
      # Use a stable tag instead of commit hash
      uses: advanced-security/maven-dependency-submission-action@v4
      with:
        # Verify this path is EXACTLY correct and matches the working-directory above
        base-directory: Awx-automation/Awx-automation