name: Maven Package

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Create settings.xml
      run: |
        cat << EOF > $GITHUB_WORKSPACE/settings.xml
        <settings>
          <servers>
            <server>
              <id>github</id>
              <username>\${env.GITHUB_ACTOR}</username>
              <password>\${env.GITHUB_TOKEN}</password>
            </server>
          </servers>
        </settings>
        EOF

    - name: Build and Deploy
      run: |
        mvn deploy -X -e -s $GITHUB_WORKSPACE/settings.xml ...
          --file Awx-automation/Awx-automation/pom.xml \
          -DskipTests \
          -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/Srigopinath-A/Awx-Auto-File
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}