# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file Awx-automation/Awx-automation/pom.xml

    - name: Unit Test
      run: mvn -B test --file Awx-automation/Awx-automation/pom.xml

    - name: Build Application
      run: |
        mvn clean --file Awx-automation/Awx-automation/pom.xml
        mvn -B package --file Awx-automation/Awx-automation/pom.xml

    - name: Build docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: Dockerfile --file Awx-automation/Awx-automation/Dockerfile
        push: false
        tags: ${{ secrets.DOCKER_LOGIN}}/Awx-auromation:test

    - name: Login to Docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: push to docker hub
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: Dockerfile --file Awx-automation/Awx-automation/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_LOGIN}}/Awx-auromation:test